import { type Task, TaskStatus, Priority } from '../types'

export const SEED_TASKS: Task[] = [
  {
    id: 'seed-001',
    title: 'Deploy Task Due Dates to the Front Line',
    description: 'Add a dueDate field to the Task type, a date picker in TaskForm, and overdue highlighting on TaskCard so deadlines are visible at a glance.',
    priority: Priority.High,
    status: TaskStatus.Backlog,
    createdAt: 1743897600000,
  },
  {
    id: 'seed-002',
    title: 'Forge the Drag-and-Drop Battle Order',
    description: 'Implement drag-and-drop across all three columns so tasks can be moved without relying solely on the advance/retreat buttons.',
    priority: Priority.High,
    status: TaskStatus.Backlog,
    createdAt: 1743897700000,
  },
  {
    id: 'seed-003',
    title: 'Unlock the Status Rune in Task Form',
    description: "Remove the read-only lock on the status field in TaskForm so users can change a task's column while editing it.",
    priority: Priority.High,
    status: TaskStatus.Backlog,
    createdAt: 1743897800000,
  },
  {
    id: 'seed-004',
    title: 'Raise the Shield of Undo — Deletion Protection',
    description: 'Add a confirmation dialog and a brief undo toast when a task is deleted to prevent accidental permanent loss.',
    priority: Priority.High,
    status: TaskStatus.Backlog,
    createdAt: 1743897900000,
  },
  {
    id: 'seed-005',
    title: 'Rally the Troops by Priority — Column Sorting',
    description: 'Add sort and filter controls to each column so tasks can be ordered by priority, due date, or creation time.',
    priority: Priority.High,
    status: TaskStatus.Backlog,
    createdAt: 1743898000000,
  },
  {
    id: 'seed-006',
    title: 'Chronicle the Fallen — Completed Task History',
    description: 'Build a Campaign Chronicle panel showing a scrollable log of all completed tasks with their completedAt timestamps and priority.',
    priority: Priority.High,
    status: TaskStatus.Backlog,
    createdAt: 1743898100000,
  },
  {
    id: 'seed-007',
    title: 'Count the Consecutive Campaigns — Streak Tracker',
    description: 'Implement a consecutive-day task completion streak with Warhammer title milestones displayed in the StatsPanel.',
    priority: Priority.High,
    status: TaskStatus.Backlog,
    createdAt: 1743898200000,
  },
  {
    id: 'seed-008',
    title: 'Issue Scrolls of Export — JSON Data Backup',
    description: 'Add a one-click export button that downloads the current app state as a JSON file to protect against localStorage loss.',
    priority: Priority.High,
    status: TaskStatus.Backlog,
    createdAt: 1743898300000,
  },
  {
    id: 'seed-009',
    title: 'Send the Outriders — Keyword Search',
    description: 'Add a search bar above the task board that filters all tasks across all columns by keyword in real time.',
    priority: Priority.Medium,
    status: TaskStatus.Backlog,
    createdAt: 1743898400000,
  },
  {
    id: 'seed-010',
    title: 'Bind the Rune of Swift Command — Keyboard Shortcuts',
    description: 'Implement keyboard shortcuts: N for new task, Escape to close modals, and arrow keys to navigate between task cards.',
    priority: Priority.Medium,
    status: TaskStatus.Backlog,
    createdAt: 1743898500000,
  },
  {
    id: 'seed-011',
    title: 'Award the Medals of Sigmar — Achievement System',
    description: 'Create milestone achievements tied to allTimeDoneCount that display as toast notifications with Warhammer-flavored titles.',
    priority: Priority.Medium,
    status: TaskStatus.Backlog,
    createdAt: 1743898600000,
  },
  {
    id: 'seed-012',
    title: 'Let Chaos Corrupt the Backlog Column',
    description: 'Visually intensify the Backlog column border color, texture, and subLabel text as the backlog task count grows to reflect mounting Chaos pressure.',
    priority: Priority.Medium,
    status: TaskStatus.Backlog,
    createdAt: 1743898700000,
  },
  {
    id: 'seed-013',
    title: 'Name Thy General — Commander Identity Setting',
    description: 'Add a settings panel where the user enters a character name woven into flavor text, achievement notifications, and the Stats Panel.',
    priority: Priority.Medium,
    status: TaskStatus.Backlog,
    createdAt: 1743898800000,
  },
  {
    id: 'seed-014',
    title: 'Mark the Neglected with the Eye of Chaos',
    description: 'Tasks that remain in Backlog beyond a configurable number of days receive an icon indicating which Chaos god has claimed them.',
    priority: Priority.Medium,
    status: TaskStatus.Backlog,
    createdAt: 1743898900000,
  },
  {
    id: 'seed-015',
    title: 'Sound the Morning Horn — Daily Briefing Modal',
    description: "Show a first-open-of-the-day modal styled as a military briefing with yesterday's completed tasks and today's high-priority items.",
    priority: Priority.Medium,
    status: TaskStatus.Backlog,
    createdAt: 1743899000000,
  },
  {
    id: 'seed-016',
    title: 'Fill the Grimoire — Expand Flavor Text Pool',
    description: 'Expand each war phase in FLAVOR_TEXTS from 3-4 strings to 10-15 unique strings to eliminate repetition for daily users.',
    priority: Priority.Medium,
    status: TaskStatus.Backlog,
    createdAt: 1743899100000,
  },
  {
    id: 'seed-017',
    title: 'Brand the Legions — Task Tags and Labels',
    description: 'Add freeform or preset tag support to tasks so they can be grouped by project, area of life, or campaign.',
    priority: Priority.Medium,
    status: TaskStatus.Backlog,
    createdAt: 1743899200000,
  },
  {
    id: 'seed-018',
    title: 'Fix the allTimeDoneCount Bug in EDIT_TASK',
    description: 'EDIT_TASK in appReducer never increments allTimeDoneCount when status changes to Done via the form. Add the same wasNotDone && isNowDone check used in MOVE_TASK.',
    priority: Priority.High,
    status: TaskStatus.Backlog,
    createdAt: 1743899250000,
  },
  {
    id: 'seed-019',
    title: 'Declare a Named Campaign — Victory Condition System',
    description: 'Let users define a named campaign with a task-completion target and end date; completing it triggers a full-screen victory sequence.',
    priority: Priority.Low,
    status: TaskStatus.Backlog,
    createdAt: 1743899300000,
  },
  {
    id: 'seed-020',
    title: 'March to Mobile — Responsive Column Layout',
    description: 'Implement a responsive layout that stacks the three task columns vertically on small screens for usable mobile access.',
    priority: Priority.Low,
    status: TaskStatus.Backlog,
    createdAt: 1743899500000,
  },
]
